name: Deploy with GitHub Pages

on:
    push: { branches: ["master", "main"] }

jobs:
    deploy:
        name: Deploy NuxtJS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install Node v18
              uses: actions/setup-node@v2
              with:
                  node-version: 18
                  cache: npm

            - name: Install Dependencies
              run: npm --production=false ci

            - name: Set Origin URL
              run: git remote set-url origin https://git:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}

            - name: Generate Nuxt Build
              run: npx nuxt generate

            - name: Deploy to Github pages
              run: npx gh-pages --dotfiles -d .output/public -u "github-actions-bot <support+actions@github.com>" -m "Deploy build"
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
