name: Deploy with GitHub Pages

on:
    push: { branches: ["master", "main"] }

jobs:
    deploy:
        name: Deploy NuxtJS
        runs-on: ubuntu-latest

        steps:
            - name: Set Origin URL
              run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

            - name: Generate Nuxt Build
              run: nuxt generate

            - name: Deploy to Github pages
              run: npx gh-pages --dotfiles -d .output/public -u "github-actions-bot <support+actions@github.com>" -m "Deploy build for commit ${{ GITHUB_SHA }}"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
